#!/usr/bin/env ruby
# frozen_string_literal: true

$LOAD_PATH << File.expand_path('../lib', __dir__)

require 'uwo_bot_service'

begin
  service = UwoBotService::BotService.new
  service.start
ensure
  service&.stop
end
