require:
  - rubocop-rspec

Layout/LineLength:
  Max: 80
Metrics/BlockLength:
  CountAsOne: ['array', 'hash', 'heredoc']
  Exclude:
    - spec/**/*
Metrics/CyclomaticComplexity:
  Max: 10
Metrics/MethodLength:
  CountAsOne: ['array', 'hash', 'heredoc']
  Max: 20
Metrics/PerceivedComplexity:
  Max: 10
RSpec/FilePath:
  Enabled: false
RSpec/VerifiedDoubles:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/DocumentationMethod:
  Enabled: false
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma
