version: '3.4'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        # On Linux, you may need to update USER_UID and USER_GID below if not your local UID is not 1000.
        USER_UID: 1000
        USER_GID: 1000
    network_mode: service:db
    env_file:
      - .env
    environment:
      RACK_ENV: production
      DATABASE_URL: db

  db:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - mongodb-data:/data/db
volumes:
  mongodb-data:
