development:
  url: <%= ENV['DATABASE_URL'] %>
  database: uwo_dictionary_bot

production:
  url: <%= ENV['DATABASE_URL'] %>
  database: uwo_dictionary_bot
  max_pool_size: <%= ENV.fetch('MAX_POOL_SIZE', 5) %>
